import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { parseTsConfig, resolveExtendsTargets } from "@/analyzer/utils/tsconfig";

describe("parseTsConfig", () => {
  it("parses JSONC with comments, trailing commas and a BOM", () => {
    const text = '﻿{\n  // generated by tsc --init\n  "compilerOptions": { "paths": { "@/*": ["src/*"], }, },\n}';
    expect(parseTsConfig("tsconfig.json", text)).toEqual({ compilerOptions: { paths: { "@/*": ["src/*"] } } });
  });

  it("returns undefined for malformed or non-object text", () => {
    expect(parseTsConfig("tsconfig.json", "{ invalid")).toBeUndefined();
    expect(parseTsConfig(String.raw`D:\repo\package.json`, "{ invalid")).toBeUndefined();
    expect(parseTsConfig("/repo/tsconfig.json", "{ invalid")).toBeUndefined();
    expect(parseTsConfig("tsconfig.json", "[1]")).toBeUndefined();
  });
});

describe("resolveExtendsTargets", () => {
  let root: string;
  let config: string;
  const write = (relative: string, content = "{}") => {
    const file = path.join(root, relative);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    return file;
  };

  beforeEach(() => {
    root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "graph-it-tsconfig-")));
    config = write("tsconfig.json");
  });
  afterEach(() => fs.rmSync(root, { recursive: true, force: true }));

  it("returns nothing when extends is absent or not a string", () => {
    expect(resolveExtendsTargets(config, undefined)).toEqual([]);
    expect(resolveExtendsTargets(config, 42)).toEqual([]);
    expect(resolveExtendsTargets(config, ["", null])).toEqual([]);
  });

  it("resolves relative specifiers with and without the .json extension", () => {
    const base = write("configs/base.json");
    const extensionless = write("configs/raw");
    expect(resolveExtendsTargets(config, "./configs/base")).toEqual([base]);
    expect(resolveExtendsTargets(config, "./configs/base.json")).toEqual([base]);
    expect(resolveExtendsTargets(config, "./configs/raw")).toEqual([extensionless]);
    expect(resolveExtendsTargets(config, base)).toEqual([base]);
  });

  it("keeps a missing relative target so its later creation can be detected", () => {
    expect(resolveExtendsTargets(config, "./missing")).toEqual([path.join(root, "missing")]);
  });

  it("resolves an array in declaration order", () => {
    const first = write("first.json");
    const second = write("second.json");
    expect(resolveExtendsTargets(config, ["./first", "./second.json"])).toEqual([first, second]);
  });

  it("resolves package specifiers through node_modules", () => {
    write("node_modules/@acme/tsconfig/package.json", '{ "name": "@acme/tsconfig", "version": "1.0.0" }');
    const subpath = write("node_modules/@acme/tsconfig/base.json");
    const packageDefault = write("node_modules/@acme/tsconfig/tsconfig.json");
    expect(resolveExtendsTargets(config, "@acme/tsconfig/base.json")).toEqual([subpath]);
    expect(resolveExtendsTargets(config, "@acme/tsconfig")).toEqual([packageDefault]);
  });

  it("keeps package targets under a symlinked config directory", () => {
    write("node_modules/@acme/tsconfig/package.json", '{ "name": "@acme/tsconfig", "version": "1.0.0" }');
    write("node_modules/@acme/tsconfig/base.json");
    const link = `${root}-link`;
    // "junction" needs no privilege on Windows and is ignored elsewhere.
    fs.symlinkSync(root, link, "junction");
    try {
      expect(resolveExtendsTargets(path.join(link, "tsconfig.json"), "@acme/tsconfig/base.json")).toEqual([
        path.join(link, "node_modules", "@acme", "tsconfig", "base.json"),
      ]);
    } finally {
      fs.rmSync(link, { force: true });
    }
  });

  it("skips package specifiers that do not resolve to a JSON config", () => {
    write("node_modules/js-only/package.json", '{ "name": "js-only", "main": "index.js" }');
    write("node_modules/js-only/index.js", "module.exports = {};");
    expect(resolveExtendsTargets(config, "js-only")).toEqual([]);
    expect(resolveExtendsTargets(config, "@missing/tsconfig")).toEqual([]);
  });
});
